# Generated by Django 4.2.7 on 2023-12-29 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('brand', models.CharField(default='', max_length=25)),
                ('title', models.CharField(default='', max_length=250)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('actual_price', models.PositiveIntegerField(default=99)),
                ('discounted_price', models.PositiveIntegerField(default=99)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.account')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
