# Generated by Django 4.2.7 on 2024-02-05 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_usersubscriptiondetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubscriptiondetail',
            name='paid',
        ),
        migrations.AlterField(
            model_name='usersubscriptiondetail',
            name='status',
            field=models.CharField(choices=[('a', 'active'), ('e', 'expired')], max_length=35),
        ),
    ]
