# Generated by Django 4.2.7 on 2024-02-06 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_remove_usersubscriptiondetail_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscriptiondetail',
            name='status',
            field=models.CharField(max_length=35),
        ),
    ]
