# Generated by Django 4.2.7 on 2024-01-30 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_subscription_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='subscription_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
