# Generated by Django 4.2.7 on 2024-01-30 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_subscription_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='permissions',
            field=models.ManyToManyField(blank=True, null=True, related_name='permission', to='user.permission'),
        ),
    ]
