# Generated by Django 4.2.7 on 2024-01-30 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='permission', to='user.permission'),
        ),
    ]
