# Generated by Django 4.2.7 on 2024-03-18 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_user_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_imported',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
