# Generated by Django 4.2.7 on 2024-02-05 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_usersubscriptiondetail'),
        ('user', '0007_user_coupon_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='coupon_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='subscription_id',
        ),
        migrations.AddField(
            model_name='user',
            name='subscription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.usersubscriptiondetail'),
        ),
    ]
