# Generated by Django 4.2.7 on 2024-02-06 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_user_city_alter_user_state'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Roll',
            new_name='Role',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='roll',
            new_name='role',
        ),
    ]
