# Generated by Django 4.2.7 on 2024-02-27 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_account_token_expires_in'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='token_expires_in',
        ),
        migrations.AddField(
            model_name='account',
            name='token_expires_in_minutes',
            field=models.IntegerField(default=180),
        ),
    ]
