# Generated by Django 4.2.7 on 2024-02-27 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_remove_account_token_expires_in_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='token_expires_in_minutes',
            new_name='token_expires_in_seconds',
        ),
    ]
