# Generated by Django 4.2.7 on 2024-03-08 21:22

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_rename_token_expires_in_minutes_account_token_expires_in_seconds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=10, null=True, validators=[user.models.phone_validator]),
        ),
    ]
